# Travis CI configuration for Django Project

language: python

python:
  - "3.4"
  - "3.5"
services:
  - mysql
env:
  -DJANGO=2.1 DB=mysql
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
